#!/usr/bin/env bash

export platforms=(
	linux_amd64
	linux_386
	linux_arm
	linux_arm_rpi
	linux_arm_vivante
	linux_mipsle
	android_arm
	android_arm64
	darwin_amd64
	darwin_arm64
	windows_amd64
	windows_386
)
